services:
  mysql:
    image: mysql:8.0 # Official MySQL image
    container_name: django_container
    restart: always # Restart if container stops
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql # Persistent data storage
  adminer:
    image: adminer
    container_name: django_adminer
    ports:
      - '8080:8080'
    depends_on:
      - mysql
volumes:
  mysql_data: